#------------- Project Metadata -------------#
# Basic information about the app package and versioning
name: cylcentral_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

#------------- Environment Requirements -------------#
environment:
  sdk: ^3.7.0

#------------- Runtime Dependencies -------------#
dependencies:

  flutter:
    sdk: flutter
    
  # State Management
  provider: ^6.1.5
  
  
  # Networking & Storage
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

 # Utilities
  intl: ^0.19.0
  url_launcher: ^6.3.1
  

  # UI Components
  badges: ^3.1.2
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0

#------------- Development Dependencies -------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/favicon.png"
  min_sdk_android: 21


#------------- Flutter Configuration -------------#
flutter:
  uses-material-design: true

  #------- Assets -------#
  assets:
    - assets/images/logo.gif
    - assets/images/favicon.png
    - assets/images/logo_name.png
    - assets/images/onboarding/onboarding1.gif
    - assets/images/onboarding/onboarding2.gif
    - assets/images/onboarding/onboarding3.gif
    - assets/images/onboarding/onboarding_bg.png
    - assets/images/onboarding/welcome_bg.png
    - assets/icons/
    - assets/fonts/

  #------- Fonts -------#
  fonts:
    - family: Poppins
      fonts:
          # Ultra Light
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
          # Light
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
          weight: 300
          # Regular
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
          weight: 400
          # Medium
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
          # Semi Bold
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
          # Bold
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
          # Extra Bold
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
          # Black
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic
          weight: 900
